---
ansible_become: true

docker_package_state: present

docker_users:
  - "{{ ansible_user | default(ansible_user_id) }}"

docker_networks:
  - name: iot_net

kafka_topic: tb-telemetry
kafka_image: "confluentinc/cp-kafka:7.5.0"
kafka_cluster_id: "MkU3OEVBNTcwNTJENDM2Qk"
kafka_container_name: kafka
kafka_dir: /opt/kafka
kafka_data_dir: /opt/kafka/data

clickhouse_image: "clickhouse/clickhouse-server:23.10"
clickhouse_dir: /opt/clickhouse
clickhouse_user: telemetry
clickhouse_password: telemetry
clickhouse_db: telemetry
clickhouse_http_port: 8123

thingsboard_image: "thingsboard/tb-postgres"
thingsboard_dir: /opt/thingsboard
thingsboard_postgres_password: tb_postgres
thingsboard_http_port: 8080
thingsboard_mqtt_port: 1883
thingsboard_devices:
  - name: drone-1
    token: drone-1-token
  - name: drone-2
    token: drone-2-token
  - name: drone-3
    token: drone-3-token

thingsboard_admin_user: tenant@thingsboard.org
thingsboard_admin_password: tenant

grafana_image: grafana/grafana-oss:11.1.0
grafana_dir: /opt/grafana
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
